version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "1702:80"
    depends_on:
      - server
    networks:
      - my_network

  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=internproject
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3308:3306"
    volumes:
      - db:/var/lib/mysql
      - ./MyDatabase.sql:/docker-entrypoint-initdb.d/MyDatabase.sql
    expose:
      - 3306
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - my_network

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8800:8800"
    environment:
      - DB_HOST=mysqldb
      - FRONTEND_URL=http://45.77.32.24:1702
    volumes:
      - ./backend:/index.js 
    networks:
      - my_network

volumes:
  db:

networks:
  my_network:
    driver: bridge