version: '3.8'

services:
  frontend:
    image: nginx:latest
    container_name: frontend
    ports:
      - "3000:3000"  # Nâng cấp frontend lên cổng 3000
    volumes:
      - ./client/build:/usr/share/nginx/html  # Ánh xạ build từ frontend
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8800:8800"  # Cổng cho backend
    volumes:
      - ./backend:/app  # Ánh xạ mã nguồn backend
    environment:
      - NODE_ENV=development
      - DB_HOST=db  # Kết nối tới db service
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=InternProject
    depends_on:
      - db  # Đảm bảo db khởi động trước backend
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"  # MySQL bên trong chạy trên cổng 3306, bên ngoài là 3307
    environment:
      MYSQL_DATABASE: InternProject
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql  # Dữ liệu MySQL được lưu trữ ngoài container
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge  # Chỉ định mạng bridge nếu cần (thường mặc định)
